/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { UserInfoWhereUniqueInput } from "../../userInfo/base/UserInfoWhereUniqueInput";
import { UserTimeTrackingRequestDetailListRelationFilter } from "../../userTimeTrackingRequestDetail/base/UserTimeTrackingRequestDetailListRelationFilter";
import { StringFilter } from "../../util/StringFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";

@InputType()
class UserTimeTrackingRequestWhereInput {
  @ApiProperty({
    required: false,
    type: DateTimeNullableFilter,
  })
  @Type(() => DateTimeNullableFilter)
  @IsOptional()
  @Field(() => DateTimeNullableFilter, {
    nullable: true,
  })
  approvedAt?: DateTimeNullableFilter;

  @ApiProperty({
    required: false,
    type: () => UserInfoWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserInfoWhereUniqueInput)
  @IsOptional()
  @Field(() => UserInfoWhereUniqueInput, {
    nullable: true,
  })
  approverInfo?: UserInfoWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => UserTimeTrackingRequestDetailListRelationFilter,
  })
  @ValidateNested()
  @Type(() => UserTimeTrackingRequestDetailListRelationFilter)
  @IsOptional()
  @Field(() => UserTimeTrackingRequestDetailListRelationFilter, {
    nullable: true,
  })
  details?: UserTimeTrackingRequestDetailListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  name?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: DateTimeNullableFilter,
  })
  @Type(() => DateTimeNullableFilter)
  @IsOptional()
  @Field(() => DateTimeNullableFilter, {
    nullable: true,
  })
  requestedAt?: DateTimeNullableFilter;

  @ApiProperty({
    required: false,
    type: () => UserInfoWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserInfoWhereUniqueInput)
  @IsOptional()
  @Field(() => UserInfoWhereUniqueInput, {
    nullable: true,
  })
  requesterInfo?: UserInfoWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: IntNullableFilter,
  })
  @Type(() => IntNullableFilter)
  @IsOptional()
  @Field(() => IntNullableFilter, {
    nullable: true,
  })
  status?: IntNullableFilter;
}

export { UserTimeTrackingRequestWhereInput as UserTimeTrackingRequestWhereInput };
