import { UserExpenseRequestUpdateManyWithoutUserInfosInput } from "./UserExpenseRequestUpdateManyWithoutUserInfosInput";
import { UserTimeOffRequestUpdateManyWithoutUserInfosInput } from "./UserTimeOffRequestUpdateManyWithoutUserInfosInput";
import { UserTimeTrackingRequestUpdateManyWithoutUserInfosInput } from "./UserTimeTrackingRequestUpdateManyWithoutUserInfosInput";
import { CompanyCalendarUpdateManyWithoutUserInfosInput } from "./CompanyCalendarUpdateManyWithoutUserInfosInput";
import { CompanyNewUpdateManyWithoutUserInfosInput } from "./CompanyNewUpdateManyWithoutUserInfosInput";
import { InputJsonValue } from "../../types";
import { CompanyRecognitionUpdateManyWithoutUserInfosInput } from "./CompanyRecognitionUpdateManyWithoutUserInfosInput";
import { UserAssetUpdateManyWithoutUserInfosInput } from "./UserAssetUpdateManyWithoutUserInfosInput";
import { UserSurveyResponseUpdateManyWithoutUserInfosInput } from "./UserSurveyResponseUpdateManyWithoutUserInfosInput";

export type UserInfoUpdateInput = {
  address?: string | null;
  approverExpenseRequest?: UserExpenseRequestUpdateManyWithoutUserInfosInput;
  approverTimeoffRequest?: UserTimeOffRequestUpdateManyWithoutUserInfosInput;
  approverTimetrackingRequest?: UserTimeTrackingRequestUpdateManyWithoutUserInfosInput;
  businessEmail?: string | null;
  citizenship?: string | null;
  city?: string | null;
  companyCalendar?: CompanyCalendarUpdateManyWithoutUserInfosInput;
  companyNews?: CompanyNewUpdateManyWithoutUserInfosInput;
  country?: string | null;
  documents?: InputJsonValue;
  educations?: InputJsonValue;
  emergencyContacts?: InputJsonValue;
  employeeNumber?: string | null;
  firstName?: string | null;
  gender?: number | null;
  jobs?: InputJsonValue;
  lastName?: string | null;
  managerId?: string | null;
  martialStatus?: number | null;
  nationality?: string | null;
  personalEmail?: string | null;
  phone?: string | null;
  postcode?: string | null;
  requesterExpenseRequest?: UserExpenseRequestUpdateManyWithoutUserInfosInput;
  requesterInfo?: CompanyRecognitionUpdateManyWithoutUserInfosInput;
  requesterTimetrackingRequest?: UserTimeTrackingRequestUpdateManyWithoutUserInfosInput;
  socialContacts?: InputJsonValue;
  timeoffs?: InputJsonValue;
  userAsset?: UserAssetUpdateManyWithoutUserInfosInput;
  userInfo?: CompanyRecognitionUpdateManyWithoutUserInfosInput;
  userSurveyResponse?: UserSurveyResponseUpdateManyWithoutUserInfosInput;
  userTimeoffRequest?: UserTimeOffRequestUpdateManyWithoutUserInfosInput;
};
