import { StringNullableFilter } from "../../util/StringNullableFilter";
import { UserExpenseRequestListRelationFilter } from "../userExpenseRequest/UserExpenseRequestListRelationFilter";
import { UserTimeOffRequestListRelationFilter } from "../userTimeOffRequest/UserTimeOffRequestListRelationFilter";
import { UserTimeTrackingRequestListRelationFilter } from "../userTimeTrackingRequest/UserTimeTrackingRequestListRelationFilter";
import { CompanyCalendarListRelationFilter } from "../companyCalendar/CompanyCalendarListRelationFilter";
import { CompanyNewListRelationFilter } from "../companyNew/CompanyNewListRelationFilter";
import { JsonFilter } from "../../util/JsonFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";
import { StringFilter } from "../../util/StringFilter";
import { CompanyRecognitionListRelationFilter } from "../companyRecognition/CompanyRecognitionListRelationFilter";
import { UserAssetListRelationFilter } from "../userAsset/UserAssetListRelationFilter";
import { UserSurveyResponseListRelationFilter } from "../userSurveyResponse/UserSurveyResponseListRelationFilter";

export type UserInfoWhereInput = {
  address?: StringNullableFilter;
  approverExpenseRequest?: UserExpenseRequestListRelationFilter;
  approverTimeoffRequest?: UserTimeOffRequestListRelationFilter;
  approverTimetrackingRequest?: UserTimeTrackingRequestListRelationFilter;
  businessEmail?: StringNullableFilter;
  citizenship?: StringNullableFilter;
  city?: StringNullableFilter;
  companyCalendar?: CompanyCalendarListRelationFilter;
  companyNews?: CompanyNewListRelationFilter;
  country?: StringNullableFilter;
  documents?: JsonFilter;
  educations?: JsonFilter;
  emergencyContacts?: JsonFilter;
  employeeNumber?: StringNullableFilter;
  firstName?: StringNullableFilter;
  gender?: IntNullableFilter;
  id?: StringFilter;
  jobs?: JsonFilter;
  lastName?: StringNullableFilter;
  managerId?: StringNullableFilter;
  martialStatus?: IntNullableFilter;
  nationality?: StringNullableFilter;
  personalEmail?: StringNullableFilter;
  phone?: StringNullableFilter;
  postcode?: StringNullableFilter;
  requesterExpenseRequest?: UserExpenseRequestListRelationFilter;
  requesterInfo?: CompanyRecognitionListRelationFilter;
  requesterTimetrackingRequest?: UserTimeTrackingRequestListRelationFilter;
  socialContacts?: JsonFilter;
  timeoffs?: JsonFilter;
  userAsset?: UserAssetListRelationFilter;
  userInfo?: CompanyRecognitionListRelationFilter;
  userSurveyResponse?: UserSurveyResponseListRelationFilter;
  userTimeoffRequest?: UserTimeOffRequestListRelationFilter;
};
