import { UserExpenseRequestCreateNestedManyWithoutUserInfosInput } from "./UserExpenseRequestCreateNestedManyWithoutUserInfosInput";
import { UserTimeOffRequestCreateNestedManyWithoutUserInfosInput } from "./UserTimeOffRequestCreateNestedManyWithoutUserInfosInput";
import { UserTimeTrackingRequestCreateNestedManyWithoutUserInfosInput } from "./UserTimeTrackingRequestCreateNestedManyWithoutUserInfosInput";
import { CompanyCalendarCreateNestedManyWithoutUserInfosInput } from "./CompanyCalendarCreateNestedManyWithoutUserInfosInput";
import { CompanyNewCreateNestedManyWithoutUserInfosInput } from "./CompanyNewCreateNestedManyWithoutUserInfosInput";
import { InputJsonValue } from "../../types";
import { CompanyRecognitionCreateNestedManyWithoutUserInfosInput } from "./CompanyRecognitionCreateNestedManyWithoutUserInfosInput";
import { UserAssetCreateNestedManyWithoutUserInfosInput } from "./UserAssetCreateNestedManyWithoutUserInfosInput";
import { UserSurveyResponseCreateNestedManyWithoutUserInfosInput } from "./UserSurveyResponseCreateNestedManyWithoutUserInfosInput";

export type UserInfoCreateInput = {
  address?: string | null;
  approverExpenseRequest?: UserExpenseRequestCreateNestedManyWithoutUserInfosInput;
  approverTimeoffRequest?: UserTimeOffRequestCreateNestedManyWithoutUserInfosInput;
  approverTimetrackingRequest?: UserTimeTrackingRequestCreateNestedManyWithoutUserInfosInput;
  businessEmail?: string | null;
  citizenship?: string | null;
  city?: string | null;
  companyCalendar?: CompanyCalendarCreateNestedManyWithoutUserInfosInput;
  companyNews?: CompanyNewCreateNestedManyWithoutUserInfosInput;
  country?: string | null;
  documents?: InputJsonValue;
  educations?: InputJsonValue;
  emergencyContacts?: InputJsonValue;
  employeeNumber?: string | null;
  firstName?: string | null;
  gender?: number | null;
  jobs?: InputJsonValue;
  lastName?: string | null;
  managerId?: string | null;
  martialStatus?: number | null;
  nationality?: string | null;
  personalEmail?: string | null;
  phone?: string | null;
  postcode?: string | null;
  requesterExpenseRequest?: UserExpenseRequestCreateNestedManyWithoutUserInfosInput;
  requesterInfo?: CompanyRecognitionCreateNestedManyWithoutUserInfosInput;
  requesterTimetrackingRequest?: UserTimeTrackingRequestCreateNestedManyWithoutUserInfosInput;
  socialContacts?: InputJsonValue;
  timeoffs?: InputJsonValue;
  userAsset?: UserAssetCreateNestedManyWithoutUserInfosInput;
  userInfo?: CompanyRecognitionCreateNestedManyWithoutUserInfosInput;
  userSurveyResponse?: UserSurveyResponseCreateNestedManyWithoutUserInfosInput;
  userTimeoffRequest?: UserTimeOffRequestCreateNestedManyWithoutUserInfosInput;
};
