import { UserExpenseRequest } from "../userExpenseRequest/UserExpenseRequest";
import { UserTimeOffRequest } from "../userTimeOffRequest/UserTimeOffRequest";
import { UserTimeTrackingRequest } from "../userTimeTrackingRequest/UserTimeTrackingRequest";
import { CompanyCalendar } from "../companyCalendar/CompanyCalendar";
import { CompanyNew } from "../companyNew/CompanyNew";
import { JsonValue } from "type-fest";
import { CompanyRecognition } from "../companyRecognition/CompanyRecognition";
import { UserAsset } from "../userAsset/UserAsset";
import { UserSurveyResponse } from "../userSurveyResponse/UserSurveyResponse";

export type UserInfo = {
  address: string | null;
  approverExpenseRequest?: Array<UserExpenseRequest>;
  approverTimeoffRequest?: Array<UserTimeOffRequest>;
  approverTimetrackingRequest?: Array<UserTimeTrackingRequest>;
  businessEmail: string | null;
  citizenship: string | null;
  city: string | null;
  companyCalendar?: Array<CompanyCalendar>;
  companyNews?: Array<CompanyNew>;
  country: string | null;
  documents: JsonValue;
  educations: JsonValue;
  emergencyContacts: JsonValue;
  employeeNumber: string | null;
  firstName: string | null;
  gender: number | null;
  id: string;
  jobs: JsonValue;
  lastName: string | null;
  managerId: string | null;
  martialStatus: number | null;
  nationality: string | null;
  personalEmail: string | null;
  phone: string | null;
  postcode: string | null;
  requesterExpenseRequest?: Array<UserExpenseRequest>;
  requesterInfo?: Array<CompanyRecognition>;
  requesterTimetrackingRequest?: Array<UserTimeTrackingRequest>;
  socialContacts: JsonValue;
  timeoffs: JsonValue;
  userAsset?: Array<UserAsset>;
  userInfo?: Array<CompanyRecognition>;
  userSurveyResponse?: Array<UserSurveyResponse>;
  userTimeoffRequest?: Array<UserTimeOffRequest>;
};
